FROM python:3.11-slim

RUN pip install --no-cache-dir mlflow>=2.13.0 boto3>=1.34.0

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////mlflow/mlflow.db", \
     "--default-artifact-root", "s3://defectvision-mlflow", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--gunicorn-opts", "--forwarded-allow-ips='*'"]
